{% set version = "0.1.1" %}

package:
  name: odvc
  version: {{ version }}

source:
  fn: odvc-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/o/odvc/odvc-{{ version }}.tar.gz
  sha256: 273054000a2926cc729f7bd3fb5caa47562cfa720d52eced7cc9b2dce7c5fc95

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - dask
    - netcdf4
    - numpy

test:
  imports:
    - odvc

about:
  home: https://github.com/pyoceans/odvc
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Ocean Dimensionless Vertical Coordinates'

extra:
  recipe-maintainers:
    - ocefpaf
