{% set version = "0.1.1" %}

package:
  name: odvc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/odvc/odvc-{{ version }}.tar.gz
  sha256: 273054000a2926cc729f7bd3fb5caa47562cfa720d52eced7cc9b2dce7c5fc95

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - dask 0.14.2
    - netcdf4
    - numpy

test:
  imports:
    - odvc

about:
  home: https://github.com/pyoceans/odvc
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Ocean Dimensionless Vertical Coordinates'

extra:
  recipe-maintainers:
    - ocefpaf
