{% set name = "odvc" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/odvc-{{ version }}.tar.gz
  sha256: d74adf7e58540ea562200f1f24c55032bebc17312f479d7714497204ba371e90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - netcdf4
    - numpy
    - python >=3.7

test:
  imports:
    - odvc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyoceans/odvc
  summary: Ocean Dimensionless Vertical Coordinates
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
