{% set version = "0.1.2" %}

package:
  name: odvc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/odvc/odvc-{{ version }}.tar.gz
  sha256: 3dea9ee46b7110a3488e838b403af9566b26262bcd57d5ac968b33c3cc14b546

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - dask >=0.14.3
    - netcdf4
    - numpy

test:
  imports:
    - odvc

about:
  home: https://github.com/pyoceans/odvc
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Ocean Dimensionless Vertical Coordinates'

extra:
  recipe-maintainers:
    - ocefpaf
