travis:
  secure:
    BINSTAR_TOKEN: h3BbaFsvh+gKUO67HJpciYescVzEBbYMaJQTu9XtRaNLJiGCT0TolNtLrxl+QkjrV4hZib8j1PvqbX++OekXIz4PN3p1rIctBc/l4TbbLoQmyyGROuSDLJTrQ23fLVEq7IeOALxBuK8cmBpazjsT495uRt4LY+nkNEHLCpvNp10nJY5MUU1hWlmBu78qgasq4OkYfA+7UigH6ezfs4BGf6BQeHUxCb2IBrBlCj8TSiW/qyG/Jm19GchFqeaEoQjeSrEM0AKIZgbbDr4XZpmgSC9ayWSxyEjROCnXytGXXe8pTFHFZtvWSZ87STCSriVZzlRfSLDKuVqRA/JEFL2LY94EbIKJBl4mng9Ks8vObB5wzTzBfmKt0B2KwDRWK7r/5wDPybAjB+H4QyfOTwOiWBLhu0G/9HQI+hOsUYIRPlpxJz2uarnqjImn0Cd3dCACKaOpu0OLIl9H+wRQT4TGM8bXeVKQ2c/ARjUIfpev+EYITVSLLPwG2vD3cxRwoOeUDDeRPCtDyzenJekBxOXWCsvVWx59A5+RrNsfggkanA3GVoUWfvYwJzwgEvkfgC1euvXYbmOjHN3xYYA8Xl2cgeYtMM1y5TflwG6msOjdmnQyYZYQ7Lo41hdNuLoXWrTrqsI3KzPB6TW0r1bMfZMZYqoHuyjJGV4b4fzPHXA+T9M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
